//! `edda export md --out <dir>` — deterministic human-readable projection of
//! the ledger (Foundry q335 EDDA-LEDGER-EXPORT1).
//!
//! Contract:
//! - SQLite stays the single source of truth. Export produces read-only files
//!   whose header names them "generated by edda — do not edit".
//! - Deterministic decision files: `decisions/<domain>.md` (and `notes.md`) are
//!   strictly byte-deterministic (same ledger + same flags ⇒ identical output)
//!   and sorted, keeping mtime / git status quiet on no-op re-exports.
//! - Freshness metadata: `INDEX.md` intentionally carries the run-time export
//!   timestamp (`- **Exported at**: ...`) and exporting machine identity
//!   (GH-806) for cross-machine provenance, and is updated on each export run.
//! - Round trip (GH-671): each decision additionally carries Scope, Authority,
//!   Reversibility and — when set — Review after, Village and Cites, because
//!   the committed-mirror import in `edda-ledger::sync` needs those fields to
//!   restore the row faithfully (original actor included). Every
//!   caller-supplied component of that encoding — the `## `key`` header and
//!   the `- **Field**: value` lines alike — is escaped (`\` and newline) by
//!   [`escape_field`], so a multi-line reason or a newline in any other field
//!   survives the single-line markdown encoding losslessly instead of emitting
//!   a line the importer would read as another field. Only the branch name and
//!   the timestamp ride raw; both are machine-constrained, and the reason is
//!   recorded at the `- **Branch/ts**:` line itself. Cites (GH-761) is read
//!   from the decision event payload, not the projected row — see
//!   [`collect_cites`].
//! - Layout:
//!   <out>/INDEX.md             — table of contents with freshness metadata
//!   <out>/decisions/<domain>.md — one file per domain (active decisions)
//!   <out>/notes.md             — chronological notes (optional)

use anyhow::{Context, Result};
use edda_core::secret_guard::redact;
use edda_ledger::Ledger;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

pub fn execute(
    repo_root: &Path,
    out_dir: &Path,
    include_notes: bool,
    machine: Option<&str>,
) -> Result<()> {
    let ledger = Ledger::open(repo_root)?;
    let ratifications = ledger.ratified_decisions_map()?;

    fs::create_dir_all(out_dir).with_context(|| format!("create out_dir {out_dir:?}"))?;
    let decisions_dir = out_dir.join("decisions");
    fs::create_dir_all(&decisions_dir).with_context(|| format!("create {decisions_dir:?}"))?;

    let active = ledger.active_decisions(None, None, None, None)?;
    let cites = collect_cites(&ledger, &active)?;
    let by_domain = group_by_domain(active);

    let mut domain_stats: Vec<(String, usize, PathBuf)> = Vec::with_capacity(by_domain.len());
    for (domain, mut rows) in by_domain {
        rows.sort_by(|a, b| a.key.cmp(&b.key));
        let path = decisions_dir.join(format!("{domain}.md"));
        let body = render_domain(&domain, &rows, &ratifications, &cites);
        write_if_changed(&path, &body)?;
        domain_stats.push((domain, rows.len(), path));
    }

    let notes_line = if include_notes {
        let note_events = ledger.iter_events_by_type("note")?;
        let path = out_dir.join("notes.md");
        let body = render_notes(&note_events);
        write_if_changed(&path, &body)?;
        Some((note_events.len(), path))
    } else {
        None
    };

    let total_decisions: usize = domain_stats.iter().map(|(_, n, _)| n).sum();
    let export_ts = now_rfc3339();
    let resolved_machine = resolve_machine(machine);
    let index_body = render_index(
        &domain_stats,
        notes_line.as_ref(),
        out_dir,
        &export_ts,
        &resolved_machine,
        total_decisions,
    );
    write_if_changed(&out_dir.join("INDEX.md"), &index_body)?;

    println!(
        "wrote {} decision files ({} total) + INDEX.md{} at {}",
        domain_stats.len(),
        total_decisions,
        if notes_line.is_some() {
            " + notes.md"
        } else {
            ""
        },
        out_dir.display(),
    );
    Ok(())
}

/// Citations (GH-761) for the rows about to be exported, keyed by event id.
///
/// `cites` lives in the decision event payload, never in the projected row
/// (`decision.cites=event-payload-not-sqlite-column`), so the export reads it
/// the same way the ratify sweep does. Without this the committed mirror
/// drops the authority chain of every decision it carries — a mirror that
/// lies by omission, against `ledger.cross-machine-projection` clause (5)
/// `quote-never-paraphrase`.
fn collect_cites(
    ledger: &Ledger,
    rows: &[edda_ledger::DecisionView],
) -> Result<BTreeMap<String, Vec<String>>> {
    let wanted: std::collections::BTreeSet<&str> =
        rows.iter().map(|r| r.event_id.as_str()).collect();
    let mut out: BTreeMap<String, Vec<String>> = BTreeMap::new();
    // Both event types that can back an active decision row. A locally
    // recorded decision is a `note`; one that arrived over a mirror is a
    // `decision_import` carrying the same `payload["decision"]["cites"]`.
    // Scanning only `note` would drop the citation chain the first time a
    // machine re-exports something it imported — the lie by omission this
    // whole field exists to prevent, moved one hop away instead of fixed.
    for kind in ["note", "decision_import"] {
        for e in ledger.iter_events_by_type(kind)? {
            if !wanted.contains(e.event_id.as_str()) {
                continue;
            }
            if let Some(list) = e.payload["decision"]["cites"].as_array() {
                let cites: Vec<String> = list
                    .iter()
                    .filter_map(|v| v.as_str().map(str::to_string))
                    .collect();
                if !cites.is_empty() {
                    out.insert(e.event_id.clone(), cites);
                }
            }
        }
    }
    Ok(out)
}

fn group_by_domain(
    rows: Vec<edda_ledger::DecisionView>,
) -> BTreeMap<String, Vec<edda_ledger::DecisionView>> {
    let mut out: BTreeMap<String, Vec<edda_ledger::DecisionView>> = BTreeMap::new();
    for row in rows {
        let dom = if row.domain.is_empty() {
            "_unclassified".to_string()
        } else {
            row.domain.clone()
        };
        out.entry(dom).or_default().push(row);
    }
    out
}

const HEADER: &str =
    "<!-- edda-ledger-export v1 — GENERATED FILE, DO NOT EDIT — SQLite ledger is authoritative -->";

fn render_domain(
    domain: &str,
    rows: &[edda_ledger::DecisionView],
    ratifications: &std::collections::BTreeMap<String, edda_ledger::RatificationInfo>,
    cites: &BTreeMap<String, Vec<String>>,
) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push('\n');
    out.push_str(&format!("# Domain: `{}`\n\n", escape_field(domain)));
    out.push_str(&format!(
        "{} active decision(s), sorted by key.\n\n",
        rows.len()
    ));
    for row in rows {
        // Secret guard the reason at export time as a belt-and-braces safety
        // — decisions written before secret_guard shipped may still carry
        // secrets in older ledgers; export must never leak them to markdown.
        let (safe_reason, _) = redact(&row.reason);
        let (safe_value, _) = redact(&row.value);
        let ts = row.ts.as_deref().unwrap_or("?");
        out.push_str(&format!("## `{}`\n\n", escape_field(&row.key)));
        out.push_str(&format!("- **Value**: `{}`\n", escape_field(&safe_value)));
        out.push_str(&format!("- **Reason**: {}\n", escape_field(&safe_reason)));
        // Branch and ts are the only two machine-generated components of this
        // encoding, so they are the only two written raw. `validate_branch_name`
        // restricts a branch to [A-Za-z0-9._/-] (edda-ledger `paths`), and `ts`
        // is the decision event's own RFC3339 stamp — the mirror's parsed `ts`
        // is never persisted, since `ImportParams` carries no ts column.
        // Neither can hold a newline, a backslash, or the "` · " separator, so
        // escaping them would only claim a hazard that does not exist.
        out.push_str(&format!("- **Branch/ts**: `{}` · {}\n", row.branch, ts));
        if let Some(info) = ratifications.get(&row.event_id) {
            out.push_str(&format!(
                "- **Governance**: ratified by {} at {}\n",
                escape_field(&info.ratified_by),
                info.ts
            ));
        } else {
            let auth = if row.authority.is_empty() {
                "agent"
            } else {
                row.authority.as_str()
            };
            out.push_str(&format!(
                "- **Governance**: unratified ({})\n",
                escape_field(&auth.to_lowercase())
            ));
        }
        // GH-671 round-trip fields: the mirror import restores these 1:1.
        //
        // Escaped, like Value and Reason, because they are caller-supplied all
        // the way down: `edda decide` trims the key and stores the rest
        // verbatim, `edda ratify --by` takes free text, and authority /
        // reversibility / review_after / village_id are unvalidated
        // `Option<String>` on the decision payload. Scope is enum-typed on the
        // decide path only — the mirror import writes that column straight
        // from parsed markdown, so one hop launders an arbitrary string into
        // it. Unescaped, a newline in any of them emits a line the importer
        // reads as another field: `authority` forges the `- **Scope**:` above
        // it and a local decision lands globally propagating, unnoticed,
        // because this import runs unattended at SessionStart.
        out.push_str(&format!(
            "- **Scope**: {}\n",
            escape_field(&row.propagation)
        ));
        out.push_str(&format!(
            "- **Authority**: {}\n",
            escape_field(&row.authority)
        ));
        out.push_str(&format!(
            "- **Reversibility**: {}\n",
            escape_field(&row.reversibility)
        ));
        if let Some(review) = &row.review_after {
            out.push_str(&format!("- **Review after**: {}\n", escape_field(review)));
        }
        if let Some(village) = &row.village_id {
            out.push_str(&format!("- **Village**: {}\n", escape_field(village)));
        }
        if let Some(list) = cites.get(&row.event_id) {
            out.push_str(&format!(
                "- **Cites**: {}\n",
                list.iter()
                    .map(|c| format!("`{}`", escape_field(c)))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        if !row.affected_paths.is_empty() {
            out.push_str(&format!(
                "- **Affected paths**: {}\n",
                row.affected_paths
                    .iter()
                    .map(|p| format!("`{}`", escape_field(p)))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        if !row.tags.is_empty() {
            out.push_str(&format!(
                "- **Tags**: {}\n",
                row.tags
                    .iter()
                    .map(|t| format!("`{}`", escape_field(t)))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        // The ORIGIN id, not this machine's row id (GH-671). An imported row's
        // local `event_id` is the `decision_import` event that carried it
        // here, so exporting that would hand every hop a fresh identity: A
        // decides, B imports (new id), B exports (B's id), A imports its own
        // ruling back as if it were B's — forever, one round per wave. The
        // origin id is what the importer's self-import guard tests, so
        // exporting it is what makes a mesh of machines converge.
        //
        // Escaped for the same reason as the fields above: a local `event_id`
        // is machine-generated, but `source_event_id` is written from parsed
        // markdown by the mirror import, so a hand-written mirror can put any
        // string in the column this line re-exports.
        out.push_str(&format!(
            "- **event_id**: `{}`\n\n",
            escape_field(row.source_event_id.as_deref().unwrap_or(&row.event_id))
        ));
    }
    out
}

fn render_notes(events: &[edda_core::Event]) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("# Notes\n\n");
    let mut sorted: Vec<&edda_core::Event> = events.iter().collect();
    sorted.sort_by(|a, b| a.ts.cmp(&b.ts));
    for ev in sorted {
        let text = ev
            .payload
            .get("text")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if text.trim().is_empty() {
            continue;
        }
        let (safe, _) = redact(text);
        out.push_str(&format!("### `{}` · `{}`\n\n", ev.ts, ev.event_id));
        out.push_str(&safe);
        out.push_str("\n\n");
    }
    out
}

fn render_index(
    domain_stats: &[(String, usize, PathBuf)],
    notes: Option<&(usize, PathBuf)>,
    out_root: &Path,
    export_ts: &str,
    machine: &str,
    total_decisions: usize,
) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("# Ledger export index\n\n");
    out.push_str(&format!("- **Exported at**: {}\n", export_ts));
    out.push_str(&format!("- **Exporting machine**: {}\n", machine));
    out.push_str(&format!("- **Total decisions**: {}\n\n", total_decisions));
    out.push_str("SQLite ledger is the single source of truth. These files exist so ");
    out.push_str("humans can `git diff` a snapshot of decisions and notes.\n\n");
    out.push_str("## Decisions by domain\n\n");
    if domain_stats.is_empty() {
        out.push_str("_(no active decisions yet)_\n\n");
    } else {
        for (domain, count, path) in domain_stats {
            let rel = path.strip_prefix(out_root).unwrap_or(path);
            out.push_str(&format!(
                "- [`{}`](./{}) — {} decision(s)\n",
                domain,
                rel.display().to_string().replace('\\', "/"),
                count
            ));
        }
        out.push('\n');
    }
    if let Some((count, path)) = notes {
        let rel = path.strip_prefix(out_root).unwrap_or(path);
        out.push_str(&format!(
            "## Notes\n\n- [`notes.md`](./{}) — {} note event(s)\n",
            rel.display().to_string().replace('\\', "/"),
            count
        ));
    }
    out
}

/// Escape a field for single-line markdown (GH-671 round trip): backslash
/// first, then newline. Inverse lives in `edda-ledger::sync::unescape_field`.
///
/// Applied to every caller-supplied component of the encoding. The pair is
/// only sound when both halves are total — escaping a field on write without
/// unescaping it on read hands the importer a literal `\n`, which is a quieter
/// corruption than the injected line it replaced, not a fix.
fn escape_field(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\n', "\\n")
}

fn resolve_machine(explicit: Option<&str>) -> String {
    if let Some(m) = explicit {
        let trimmed = m.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    if let Ok(m) = std::env::var("EDDA_MACHINE") {
        let trimmed = m.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    if let Ok(m) = std::env::var("COMPUTERNAME") {
        let trimmed = m.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    if let Ok(m) = std::env::var("HOSTNAME") {
        let trimmed = m.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    "unknown".to_string()
}

fn now_rfc3339() -> String {
    time::OffsetDateTime::now_utc()
        .format(&time::format_description::well_known::Rfc3339)
        .unwrap_or_else(|_| "unknown".to_string())
}

/// Write only when content differs — keeps mtime / git status quiet on no-op re-exports.
fn write_if_changed(path: &Path, body: &str) -> Result<()> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == body {
            return Ok(());
        }
    }
    fs::write(path, body).with_context(|| format!("write {path:?}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use edda_ledger::DecisionView;

    fn dec(key: &str, value: &str, domain: &str, paths: Vec<&str>) -> DecisionView {
        DecisionView {
            event_id: format!("evt_{}", key.replace('.', "_")),
            branch: "main".into(),
            ts: Some("2026-07-08T00:00:00Z".into()),
            key: key.into(),
            value: value.into(),
            reason: "why".into(),
            domain: domain.into(),
            status: "active".into(),
            authority: "human".into(),
            reversibility: "medium".into(),
            affected_paths: paths.into_iter().map(String::from).collect(),
            tags: vec![],
            propagation: "local".into(),
            supersedes_id: None,
            review_after: None,
            village_id: None,
            source_event_id: None,
        }
    }

    #[test]
    fn group_by_domain_buckets_and_fallback_unclassified() {
        let rows = vec![
            dec("a.x", "1", "a", vec![]),
            dec("b.x", "1", "b", vec![]),
            dec("orphan", "1", "", vec![]),
        ];
        let grouped = group_by_domain(rows);
        assert_eq!(grouped.get("a").unwrap().len(), 1);
        assert_eq!(grouped.get("b").unwrap().len(), 1);
        assert_eq!(grouped.get("_unclassified").unwrap().len(), 1);
    }

    #[test]
    fn render_domain_names_all_columns_including_affected_paths() {
        let rows = vec![dec("db.engine", "sqlite", "db", vec!["src/db.rs"])];
        let md = render_domain(
            "db",
            &rows,
            &std::collections::BTreeMap::new(),
            &BTreeMap::new(),
        );
        assert!(md.contains("GENERATED FILE"));
        assert!(md.contains("# Domain: `db`"));
        assert!(md.contains("`db.engine`"));
        assert!(md.contains("`sqlite`"));
        assert!(md.contains("`src/db.rs`"));
        assert!(md.contains("`evt_db_engine`"));
        assert!(md.contains("- **Governance**: unratified (human)"));
    }

    /// GH-671: the mirror import restores Scope/Authority/Reversibility (and
    /// Review after / Village when set) — so export must emit them.
    #[test]
    fn render_domain_emits_round_trip_fields_for_mirror_import() {
        let mut row = dec(
            "fleet.lane-profile",
            "agent-actor-is-the-profile",
            "fleet",
            vec![],
        );
        row.propagation = "local".into();
        row.authority = "agent".into();
        row.reversibility = "hard".into();
        row.review_after = Some("2027-01-01".into());
        row.village_id = Some("village-alpha".into());
        let md = render_domain(
            "fleet",
            &[row],
            &std::collections::BTreeMap::new(),
            &BTreeMap::new(),
        );
        assert!(md.contains("- **Scope**: local"), "{md}");
        assert!(md.contains("- **Authority**: agent"), "{md}");
        assert!(md.contains("- **Reversibility**: hard"), "{md}");
        assert!(md.contains("- **Review after**: 2027-01-01"), "{md}");
        assert!(md.contains("- **Village**: village-alpha"), "{md}");
    }

    /// Multi-line reasons and backslashes must survive the single-line
    /// markdown encoding losslessly (quote-never-paraphrase).
    #[test]
    fn render_domain_escapes_newlines_and_backslashes_in_value_and_reason() {
        let mut row = dec("esc.k", "a\\b\nc", "esc", vec![]);
        row.reason = "r1\nr2 \\ path".into();
        let md = render_domain(
            "esc",
            &[row],
            &std::collections::BTreeMap::new(),
            &BTreeMap::new(),
        );
        assert!(
            md.contains("- **Value**: `a\\\\b\\nc`"),
            "escaped value: {md}"
        );
        assert!(
            md.contains("- **Reason**: r1\\nr2 \\\\ path"),
            "escaped reason: {md}"
        );
        assert!(
            !md.contains("a\nb"),
            "raw newline must not leak into the file"
        );
    }

    #[test]
    fn render_domain_scrubs_secrets_in_reason() {
        let mut row = dec("test.key", "val", "test", vec![]);
        row.reason = "temp token sk-abcdefghijklmnopqrstuvwxyz012345".into();
        let md = render_domain(
            "test",
            &[row],
            &std::collections::BTreeMap::new(),
            &BTreeMap::new(),
        );
        assert!(
            md.contains("[REDACTED:openai_api_key]"),
            "export must not leak old secrets: {md}"
        );
        assert!(!md.contains("sk-abcdefghijklmnopqrstuvwxyz012345"));
    }

    #[test]
    fn render_index_lists_domains_with_counts() {
        let stats = vec![
            ("a".to_string(), 2, PathBuf::from("/root/decisions/a.md")),
            ("b".to_string(), 5, PathBuf::from("/root/decisions/b.md")),
        ];
        let md = render_index(
            &stats,
            None,
            Path::new("/root"),
            "2026-09-04T00:00:00Z",
            "test-host",
            7,
        );
        assert!(md.contains("`a`"));
        assert!(md.contains("2 decision"));
        assert!(md.contains("`b`"));
        assert!(md.contains("5 decision"));
        assert!(md.contains("- **Exported at**: 2026-09-04T00:00:00Z"));
        assert!(md.contains("- **Exporting machine**: test-host"));
        assert!(md.contains("- **Total decisions**: 7"));
    }

    #[test]
    fn render_index_notes_line_when_present() {
        let notes = Some((7usize, PathBuf::from("/root/notes.md")));
        let md = render_index(
            &[],
            notes.as_ref(),
            Path::new("/root"),
            "2026-09-04T00:00:00Z",
            "test-host",
            0,
        );
        assert!(md.contains("7 note event"));
        assert!(md.contains("notes.md"));
    }

    #[test]
    fn render_index_no_notes_line_when_absent() {
        let md = render_index(
            &[],
            None,
            Path::new("/root"),
            "2026-09-04T00:00:00Z",
            "test-host",
            0,
        );
        assert!(!md.contains("notes.md"));
    }

    #[test]
    fn write_if_changed_skips_when_body_matches() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("x.md");
        fs::write(&path, "hello").unwrap();
        let before = fs::metadata(&path).unwrap().modified().unwrap();
        // sleep enough for mtime to change if we did rewrite
        std::thread::sleep(std::time::Duration::from_millis(50));
        write_if_changed(&path, "hello").unwrap();
        let after = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(before, after, "identical body must not rewrite");
    }

    #[test]
    fn write_if_changed_rewrites_when_body_differs() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("y.md");
        fs::write(&path, "old").unwrap();
        write_if_changed(&path, "new").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "new");
    }

    #[test]
    fn render_domain_output_is_deterministic() {
        let rows = vec![
            dec("z.last", "x", "z", vec![]),
            dec("a.first", "y", "a", vec![]),
        ];
        // Simulate the sort done in execute()
        let mut a = rows.clone();
        a.sort_by(|x, y| x.key.cmp(&y.key));
        let mut b = rows;
        b.sort_by(|x, y| x.key.cmp(&y.key));
        assert_eq!(
            render_domain(
                "mix",
                &a,
                &std::collections::BTreeMap::new(),
                &BTreeMap::new()
            ),
            render_domain(
                "mix",
                &b,
                &std::collections::BTreeMap::new(),
                &BTreeMap::new()
            )
        );
    }

    #[test]
    fn export_distinguishes_ratified_from_unratified_and_stamps_index() {
        let dir = tempfile::tempdir().unwrap();
        let repo_root = dir.path().join("repo");
        fs::create_dir_all(&repo_root).unwrap();
        let ledger = Ledger::open_or_init(&repo_root).unwrap();

        // 1. Unratified decision
        let dp_unrat = edda_core::types::DecisionPayload {
            key: "auth.session_ttl".to_string(),
            value: "3600".to_string(),
            reason: Some("working proposal".to_string()),
            scope: None,
            authority: Some("agent".to_string()),
            affected_paths: None,
            tags: None,
            review_after: None,
            reversibility: None,
            village_id: None,
            cites: None,
        };
        let p1 = ledger.last_event_hash().unwrap();
        let ev1 = edda_core::event::new_decision_event("main", p1.as_deref(), "system", &dp_unrat)
            .unwrap();
        ledger.append_event(&ev1).unwrap();

        // 2. Ratified decision
        let dp_rat = edda_core::types::DecisionPayload {
            key: "auth.method".to_string(),
            value: "oauth".to_string(),
            reason: Some("Proposal - operator ratifies.".to_string()),
            scope: None,
            authority: Some("agent".to_string()),
            affected_paths: None,
            tags: None,
            review_after: None,
            reversibility: None,
            village_id: None,
            cites: None,
        };
        let p2 = ledger.last_event_hash().unwrap();
        let ev2 =
            edda_core::event::new_decision_event("main", p2.as_deref(), "system", &dp_rat).unwrap();
        ledger.append_event(&ev2).unwrap();

        // Ratify auth.method
        let p3 = ledger.last_event_hash().unwrap();
        let ev3 = edda_core::event::new_decision_ratify_event(
            "main",
            p3.as_deref(),
            "auth.method",
            "Tim",
            None,
        )
        .unwrap();
        ledger.append_event(&ev3).unwrap();
        drop(ledger);

        let out_dir = dir.path().join("export");
        execute(&repo_root, &out_dir, false, Some("host-alpha")).unwrap();

        let auth_md = fs::read_to_string(out_dir.join("decisions/auth.md")).unwrap();
        assert!(
            auth_md.contains("- **Governance**: ratified by Tim"),
            "ratified decision must state ratifier in governance field: {auth_md}"
        );
        assert!(
            auth_md.contains("- **Governance**: unratified"),
            "unratified decision must state unratified in governance field: {auth_md}"
        );

        let index_md = fs::read_to_string(out_dir.join("INDEX.md")).unwrap();
        assert!(
            index_md.contains("- **Exported at**:"),
            "INDEX.md must have export timestamp: {index_md}"
        );
        assert!(
            index_md.contains("- **Exporting machine**: host-alpha"),
            "INDEX.md must have exporting machine: {index_md}"
        );
        assert!(
            index_md.contains("- **Total decisions**: 2"),
            "INDEX.md must have total decision count: {index_md}"
        );
    }

    #[test]
    fn export_decisions_are_byte_deterministic_across_repeated_runs() {
        let dir = tempfile::tempdir().unwrap();
        let repo_root = dir.path().join("repo");
        fs::create_dir_all(&repo_root).unwrap();
        let ledger = Ledger::open_or_init(&repo_root).unwrap();

        let dp = edda_core::types::DecisionPayload {
            key: "db.engine".to_string(),
            value: "sqlite".to_string(),
            reason: Some("local dev".to_string()),
            scope: None,
            authority: Some("agent".to_string()),
            affected_paths: None,
            tags: None,
            review_after: None,
            reversibility: None,
            village_id: None,
            cites: None,
        };
        let ev = edda_core::event::new_decision_event("main", None, "system", &dp).unwrap();
        ledger.append_event(&ev).unwrap();
        drop(ledger);

        let out_dir = dir.path().join("export");
        execute(&repo_root, &out_dir, false, Some("host-alpha")).unwrap();

        let db_md_first = fs::read_to_string(out_dir.join("decisions/db.md")).unwrap();

        // Run export again on unchanged ledger
        execute(&repo_root, &out_dir, false, Some("host-alpha")).unwrap();

        let db_md_second = fs::read_to_string(out_dir.join("decisions/db.md")).unwrap();
        let index_second = fs::read_to_string(out_dir.join("INDEX.md")).unwrap();

        // decisions/*.md is strictly byte-deterministic
        assert_eq!(
            db_md_first, db_md_second,
            "decision markdown files must be identical on no-op re-export"
        );
        // INDEX.md retains structure and machine provenance
        assert!(index_second.contains("- **Exporting machine**: host-alpha"));
        assert!(index_second.contains("- **Total decisions**: 1"));
    }

    /// GH-671 R5: the mirror's single-line `- **Field**: value` encoding must
    /// be **total**, not total for two of its fields.
    ///
    /// Value and Reason were escaped; key, Scope, Authority, Reversibility,
    /// Review after and Village rode raw into the same encoding and were not
    /// unescaped on import. A newline in any of them emits an extra line that
    /// the importer reads as a *field*, so the imported row differs from the
    /// source row — silently, because this import runs unattended at
    /// SessionStart. Two of the injections below are load-bearing rather than
    /// decorative: `authority` forges the `- **Scope**:` line that precedes it
    /// (a local decision arrives globally propagating) and `village_id` forges
    /// `- **Reversibility**:`, and in both cases the forged line lands *after*
    /// the real one and therefore wins.
    ///
    /// Round trip, not render inspection: A decides, A exports, B imports, and
    /// B's row must equal A's field for field.
    #[test]
    fn export_import_round_trip_is_total_for_newlines_and_backslashes() {
        let dir = tempfile::tempdir().unwrap();
        let a_root = dir.path().join("machine-a");
        let b_root = dir.path().join("machine-b");
        fs::create_dir_all(&a_root).unwrap();
        fs::create_dir_all(&b_root).unwrap();

        // Every field here is caller-supplied: `edda decide` trims the key and
        // secret-guards value/reason, and stores the rest verbatim — no
        // validation rejects a newline in any of them (see the decision-row
        // derivation in edda-ledger `sqlite_store::events`).
        let a = Ledger::open_or_init(&a_root).unwrap();
        let dp = edda_core::types::DecisionPayload {
            key: "esc.multi\nline \\ key".to_string(),
            value: "v1\nv2 \\ back".to_string(),
            reason: Some("r1\nr2 \\ back".to_string()),
            scope: None,
            authority: Some("agent\n- **Scope**: global".to_string()),
            affected_paths: Some(vec!["crates/a\\b/**".to_string()]),
            tags: Some(vec!["t1\nt2 \\ x".to_string()]),
            review_after: Some("2027-01-01\ntrailing".to_string()),
            reversibility: Some("hard\\ish".to_string()),
            village_id: Some("village-a\\one\n- **Reversibility**: forged".to_string()),
            cites: None,
        };
        let ev = edda_core::event::new_decision_event("main", None, "system", &dp).unwrap();
        a.append_event(&ev).unwrap();
        let source = a.active_decisions(None, None, None, None).unwrap();
        assert_eq!(source.len(), 1, "one decision on machine A");
        drop(a);

        let mirror = a_root.join("docs").join("decisions");
        execute(&a_root, &mirror, false, Some("host-a")).unwrap();

        let b = Ledger::open_or_init(&b_root).unwrap();
        let imported = edda_ledger::sync::sync_from_mirror(
            &b,
            &edda_ledger::sync::MirrorSource {
                mirror_dir: mirror.clone(),
            },
            false,
        )
        .unwrap();
        assert_eq!(
            imported.imported.len(),
            1,
            "exactly one decision crosses the mirror"
        );

        let landed = b.active_decisions(None, None, None, None).unwrap();
        assert_eq!(landed.len(), 1, "one decision on machine B: {landed:#?}");
        let (before, after) = (&source[0], &landed[0]);

        // The escalation first: a forged line changes what the row *means*.
        assert_eq!(
            after.propagation, before.propagation,
            "a newline in authority must not forge a Scope line"
        );
        assert_eq!(
            after.reversibility, before.reversibility,
            "a newline in village_id must not forge a Reversibility line"
        );
        assert_eq!(after.key, before.key, "key rides the `## `key`` header");
        assert_eq!(after.value, before.value);
        assert_eq!(after.reason, before.reason);
        assert_eq!(after.authority, before.authority);
        assert_eq!(after.review_after, before.review_after);
        assert_eq!(after.village_id, before.village_id);
        assert_eq!(after.tags, before.tags);
        assert_eq!(after.affected_paths, before.affected_paths);
        // The origin identity is what makes the mesh converge, so it has to
        // survive the same encoding the fields do.
        assert_eq!(
            after.source_event_id.as_deref(),
            Some(before.event_id.as_str())
        );
    }

    #[test]
    fn resolve_machine_precedence() {
        // Explicit non-empty always wins
        assert_eq!(resolve_machine(Some("custom-box")), "custom-box");
        assert_eq!(resolve_machine(Some("  spaced-box  ")), "spaced-box");

        // Whitespace-only falls through to env / fallback
        let fallback = resolve_machine(None);
        assert_eq!(resolve_machine(Some("   ")), fallback);
    }
}
